#%RAML 1.0

# AMWA NMOS Template Specification: Example API
# (c) AMWA 2018

title: Example
baseUri: http://api.example.com/x-nmos/example/{version}
version: v1.0
mediaType: application/json

documentation:
  - title: Overview
    content: |
      This is an example API so the template works
/:
  displayName: Base
  get:
    description: List of paths available from this API
    responses:
      200:
        body:
          example: !include ../examples/exampleapi-v1.0-base-get-200.json
          type: !include schemas/exampleapi-base.json
